export const CALL = {
  OUTGOING_REQUEST: 'OUTGOING_REQUEST',
  OUTGOING_SUCCESS: 'OUTGOING_SUCCESS',
  OUTGOING_FAILURE: 'OUTGOING_FAILURE',
  INCOMING_REQUEST: 'INCOMING_REQUEST',
  INCOMING_SUCCESS: 'INCOMING_SUCCESS',
  INCOMING_FAILURE: 'INCOMING_FAILURE',
};
