export const USER = {
  GET_FCM_REQUEST: 'GET_FCM_REQUEST',
  GET_FCM_SUCCESS: 'GET_FCM_SUCCESS',
  GET_FCM_FAILURE: 'GET_FCM_FAILURE',
  FIND_BY_FCM_REQUEST: 'FIND_BY_FCM_REQUEST',
  FIND_BY_FCM_SUCCESS: 'FIND_BY_FCM_SUCCESS',
  FIND_BY_FCM_FAILURE: 'FIND_BY_FCM_FAILURE',
  SET_MOBILE: 'SET_MOBILE',
};
